XBE_TITLE = XMusic
GEN_XISO = $(XBE_TITLE).iso
SRCS += player.c
NXDK_DIR = /home/$(USERNAME)/nxdk
NXDK_SDL = y
NXDK_CXX = y

all_local: cp_sound all

include $(NXDK_DIR)/Makefile

cp_sound:
	@mkdir -p $(OUTPUT_DIR)
	@mkdir -p $(OUTPUT_DIR)/Music
	cp *.wav $(OUTPUT_DIR)/Music/
	cp *.png $(OUTPUT_DIR)
	cp *.ttf $(OUTPUT_DIR)