XBE_TITLE = XMusic
GEN_XISO = $(XBE_TITLE).iso

SRCS += main.cpp

SRCS += implementations/software/SDL/standard/player_software_SDL_mixer.cpp
SRCS += implementations/software/SDL/standard/sourcePicker_software_SDL_FilesystemX.cpp
SRCS += implementations/software/SDL/standard/system_software_SDL.cpp
CXXFLAGS += -DUSE_SOFTWARE_SDL_STANDARD=1

NXDK_DIR = /home/$(USER)/nxdk
NXDK_SDL = y
NXDK_SDL_MIXER = y
NXDK_CXX = y

all_local: cp_sound all

include $(NXDK_DIR)/Makefile

cp_sound:
	@mkdir -p $(OUTPUT_DIR)
	@mkdir -p $(OUTPUT_DIR)/Music
	cp *.wav $(OUTPUT_DIR)/Music/
	cp resources/*.png $(OUTPUT_DIR)
	cp resources/*.ttf $(OUTPUT_DIR)
