name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get submodules
      run: |
        git submodule init
        git submodule update --recursive
    - name: Install dependencies
      run: sudo apt install gcc-8 libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev
    - name: Prepare source to upload artifact
      run: |
        mkdir source
        cp --recursive * source/
    - name: Compile
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: XMusic-Linux64
        path: build/**